export const WINE_COUNTRIES: string[] = [
  'Italien',
  'Frankreich',
  'Deutschland',
  'Spanien',
  'Portugal',
  'Österreich',
  'Schweiz',
  'USA',
  'Argentinien',
  'Chile',
  'Südafrika',
  'Australien',
  'Neuseeland',
  'Ungarn',
  'Griechenland',
  'Slowenien',
  'Kroatien',
]

export const WINE_REGIONS: Record<string, string[]> = {
  'Italien': [
    'Toskana',
    'Piemont',
    'Venetien',
    'Sizilien',
    'Kampanien',
    'Apulien',
    'Sardinien',
    'Friaul-Julisch Venetien',
    'Trentino-Südtirol',
    'Lombardei',
    'Umbrien',
    'Marken',
    'Latium',
    'Abruzzen',
    'Emilia-Romagna',
    'Ligurien',
    'Kalabrien',
    'Basilicata',
    'Molise',
  ],
  'Frankreich': [
    'Bordeaux',
    'Burgund',
    'Champagne',
    'Elsass',
    'Loire',
    'Rhônetal',
    'Provence',
    'Languedoc-Roussillon',
    'Beaujolais',
    'Südwestfrankreich',
    'Jura',
    'Savoyen',
  ],
  'Deutschland': [
    'Mosel',
    'Rheingau',
    'Rheinhessen',
    'Pfalz',
    'Baden',
    'Württemberg',
    'Franken',
    'Nahe',
    'Ahr',
    'Mittelrhein',
    'Sachsen',
    'Saale-Unstrut',
  ],
  'Spanien': [
    'Rioja',
    'Ribera del Duero',
    'Priorat',
    'Galicien',
    'Penedès',
    'Rías Baixas',
    'Jerez',
    'Toro',
    'Navarra',
    'Bierzo',
    'Rueda',
    'Jumilla',
  ],
  'Portugal': [
    'Douro',
    'Alentejo',
    'Vinho Verde',
    'Dão',
    'Bairrada',
    'Setúbal',
    'Algarve',
    'Lissabon',
  ],
  'Österreich': [
    'Wachau',
    'Kamptal',
    'Kremstal',
    'Weinviertel',
    'Burgenland',
    'Steiermark',
    'Wien',
    'Traisental',
    'Wagram',
  ],
  'USA': [
    'Napa Valley',
    'Sonoma County',
    'Willamette Valley',
    'Columbia Valley',
    'Paso Robles',
    'Santa Barbara County',
    'Finger Lakes',
  ],
  'Argentinien': [
    'Mendoza',
    'Salta',
    'San Juan',
    'Patagonien',
    'La Rioja',
  ],
  'Chile': [
    'Maipo',
    'Colchagua',
    'Casablanca',
    'Maule',
    'Aconcagua',
    'Elqui',
  ],
  'Südafrika': [
    'Stellenbosch',
    'Franschhoek',
    'Paarl',
    'Swartland',
    'Walker Bay',
  ],
  'Australien': [
    'Barossa Valley',
    'McLaren Vale',
    'Clare Valley',
    'Yarra Valley',
    'Margaret River',
    'Hunter Valley',
  ],
  'Neuseeland': [
    'Marlborough',
    'Hawke\'s Bay',
    'Central Otago',
  ],
  'Ungarn': [
    'Tokaj',
    'Eger',
    'Villány',
  ],
}

export const GRAPE_VARIETIES: string[] = [
  // Rot – Italienisch
  'Sangiovese',
  'Nebbiolo',
  'Barbera',
  'Dolcetto',
  'Montepulciano',
  'Primitivo',
  'Aglianico',
  'Nero d\'Avola',
  'Cannonau',
  'Corvina',
  'Nerello Mascalese',
  'Sagrantino',
  // Rot – International
  'Cabernet Sauvignon',
  'Merlot',
  'Syrah',
  'Grenache',
  'Tempranillo',
  'Malbec',
  'Pinot Noir',
  'Zinfandel',
  'Touriga Nacional',
  'Blaufränkisch',
  'Zweigelt',
  'Gamay',
  'Carignan',
  // Weiß – Italienisch
  'Vermentino',
  'Verdicchio',
  'Trebbiano',
  'Cortese',
  'Arneis',
  'Falanghina',
  'Fiano',
  'Greco di Tufo',
  'Pinot Grigio',
  'Garganega',
  'Catarratto',
  // Weiß – International
  'Riesling',
  'Chardonnay',
  'Sauvignon Blanc',
  'Grüner Veltliner',
  'Gewürztraminer',
  'Pinot Blanc',
  'Viognier',
  'Chenin Blanc',
  'Albariño',
  'Muscat',
  'Welschriesling',
  'Grauburgunder',
  'Weißburgunder',
]
